---

- name: Install brew packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
    state: latest
  with_items: "{{ golang_brew_packages }}"
  tags:
    - golang
    - brew
