---

- name: Install brew packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
    state: latest
  with_items: "{{ python_brew_packages }}"
  tags:
    - python
    - python3
    - brew

- name: Upgrade pip
  become: yes
  command: "pip install --upgrade pip"
  tags:
    - python

- name: Upgrade pip3
  become: yes
  command: "pip3 install --upgrade pip"
  tags:
    - python
    - python3

- name: Install system python packages
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ python_packages }}"
  tags:
    - python

- name: Install system python3 packages
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  with_items: "{{ python3_packages }}"
  tags:
    - python
    - python3

- name: Install python versions via pyenv
  shell: "if [ ! `pyenv versions | grep {{ item }}` ]; then {{ python_pyenv_install_cmd }} {{ item }}; fi"
  with_items: "{{ python_pyenv_versions }}"
  when: python_use_pyenv
  tags:
    - python
