---
- name: Tap homebrew
  homebrew_tap:
    name: caskroom/versions
  tags:
    - elasticsearch
    - brew-tap

- name: Install java8 homebrew cask packages
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    install_options: "{{ item.install_options | default('') }}"
  with_items: "{{ elasticsearch_brew_cask_applications }}"
  ignore_errors: True
  tags:
    - elasticsearch
    - brew-cask

- name: Install brew packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
    state: "{{ item.state | default('latest') }}"
  with_items: "{{ elasticsearch_brew_packages }}"
  tags:
    - elasticsearch
    - brew
