---
- name: Enable to execute sudo without password
  become: True
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%admin\s'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags:
    - base
    - sudo

- name: Update homebrew
  command: "brew update"
  tags:
    - base
    - brew
    - brew-cask

- name: Install base homebrew packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
    state: "{{ item.state | default('latest') }}"
  with_items: "{{ base_brew_packages }}"
  tags:
    - base
    - brew

- name: Install brew cask applications
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    install_options: "{{ item.install_options | default('') }}"
  with_items: "{{ base_brew_cask_applications }}"
  ignore_errors: True
  tags:
    - base
    - brew-cask

- name: Change shell config
  become: yes
  lineinfile:
    path: /etc/shells
    state: present
    line: "{{ base_default_shell }}"
  tags:
    - base
    - shell

- name: Change default shell
  become: yes
  command: "chsh -s {{ base_default_shell }} {{ ansible_user }}"
  tags:
    - base
    - shell
